# Generated by Django 2.2.2 on 2020-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
