# Generated by Django 2.2.2 on 2020-03-27 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phase', models.CharField(choices=[('UD', 'Under Development'), ('UC', 'Under Construction'), ('RTB', 'Real Time Bidding'), ('COD', 'Cash On Delivery')], max_length=3)),
                ('mw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('budget_revenue', models.DecimalField(decimal_places=3, max_digits=11)),
                ('budget_cogs', models.DecimalField(decimal_places=3, max_digits=11)),
                ('cash_out_no_vat', models.DecimalField(decimal_places=3, max_digits=11)),
                ('pct_of_completion', models.DecimalField(decimal_places=3, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='projects', related_query_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
